migrate book reports to game reports

diff --git a/dev-scripts/check-seo-metadata b/dev-scripts/check-seo-metadata
--- a/dev-scripts/check-seo-metadata
+++ b/dev-scripts/check-seo-metadata
@@ -27,7 +27,7 @@ fi
 #   exit 1;
 # fi
 
-# if ! egrep '"og:title".*="Book Report: Happy City by Charles Montgomery"' "${BUILD_DIR}/book-reports/happy-city/index.html"; then
-#   echo "ERROR: Book report does not have expected opengraph title";
+# if ! egrep '"og:title".*="Game Report: Happy City by Charles Montgomery"' "${BUILD_DIR}/game-reports/happy-city/index.html"; then
+#   echo "ERROR: Game report does not have expected opengraph title";
 #   exit 1;
 # fi
